pub use winnow::stream::{LocatingSlice, Stateful};

/// The parser input type for nanachi-generated parsers.
///
/// `S` is the grammar-specific state struct generated by `nanachi_generator`.
/// It wraps winnow's `Stateful<LocatingSlice<&str>, S>` so that generated
/// code can track both source position and parsing state.
pub type Input<'i, S> = Stateful<LocatingSlice<&'i str>, S>;
