name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "."

      - name: Test
        run: cargo test --workspace

      - name: Check Fuzz Targets
        run: cargo check -p faputa_fuzz --bins --features fuzzing
